schema: spec-driven
created: 2026-07-12
created_by: Jacob Mei <259817728+notoriouslab@users.noreply.github.com>
archived_by: Jacob Mei <259817728+notoriouslab@users.noreply.github.com>
archived_at: 2026-07-13
